/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Supplier;

import dao.DonHangDAO;
import dao.NhaCungCapDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class ChoVanChuyenFrame extends javax.swing.JFrame {

    /**
     * Creates new form MyTransfer
     */
    public ChoVanChuyenFrame() {
        initComponents();
        init();
    }
    DefaultTableModel model = new DefaultTableModel();

    int xx,yy;
    DonHangDAO dhDAO=new DonHangDAO();
    NhaCungCapDAO nccDAO=new NhaCungCapDAO();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDonHang = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jButtonVanChuyen = new javax.swing.JButton();
        jTextFieldIDKhachHang = new javax.swing.JTextField();
        jTextFieldIDDonHang = new javax.swing.JTextField();
        jTextFieldSanPham = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDiaChi = new javax.swing.JTextField();
        jTextFieldtenKhachHang = new javax.swing.JTextField();
        jTextFieldSDT = new javax.swing.JTextField();
        jTextFieldTrangThai = new javax.swing.JTextField();
        jTextFieldSL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldNgayMua = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldTong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Đơn hàng", "ID Sản phẩm", "Tên sản phẩm", "ID Khách hàng", "Tên khách hàng", "Địa chỉ", "Số điện thoại", "Số lượng", "Giá", "Tổng", "Ngày mua", "Ngày nhận", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true, false, false, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDonHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDonHang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1500, 430));

        jLabel11.setFont(new java.awt.Font("Snap ITC", 1, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("X");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 10, -1, -1));

        jButtonVanChuyen.setBackground(new java.awt.Color(255, 255, 0));
        jButtonVanChuyen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonVanChuyen.setForeground(new java.awt.Color(255, 0, 0));
        jButtonVanChuyen.setText("Xác nhận vận chuyển");
        jButtonVanChuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVanChuyenActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVanChuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 600, 200, 30));

        jTextFieldIDKhachHang.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldIDKhachHang.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldIDKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDKhachHangKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldIDKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 160, -1));

        jTextFieldIDDonHang.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldIDDonHang.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldIDDonHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDDonHangKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldIDDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 160, -1));

        jTextFieldSanPham.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldSanPham.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldSanPham.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSanPhamKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, 160, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Sản phẩm");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 100, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Khách hàng");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 100, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("ID Đơn hàng");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 100, -1));

        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 530, 160, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Trạng thái");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 580, 100, -1));

        jTextFieldDiaChi.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldDiaChi.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldDiaChi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldDiaChiKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, 160, -1));

        jTextFieldtenKhachHang.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldtenKhachHang.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldtenKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldtenKhachHangKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldtenKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, 160, -1));

        jTextFieldSDT.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldSDT.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldSDT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSDTKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, 160, -1));

        jTextFieldTrangThai.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldTrangThai.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldTrangThai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTrangThaiKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 600, 160, -1));

        jTextFieldSL.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldSL.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldSL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSLKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldSL, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 600, 160, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Số lượng");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 580, 100, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("ID Khách hàng");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 100, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Địa chỉ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, 100, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Tổng");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 507, 100, 20));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Số điện thoại");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 580, 100, -1));

        jTextFieldNgayMua.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNgayMua.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldNgayMua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNgayMuaKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldNgayMua, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, 160, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Ngày mua");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 100, -1));

        jTextFieldTong.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldTong.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jTextFieldTong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTongKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldTong, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 530, 160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1592, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void init(){
    
        String email=GiaoDienQuanLyNhaCungCapFrame.jLabelEmail.getText();

        dhDAO.setNhaCungCap(jTableDonHang,email);
    }
    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x=evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jButtonVanChuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVanChuyenActionPerformed
        int select = jTableDonHang.getSelectedRow();
        String trangthai= jTextFieldTrangThai.getText().toString(); 
        model = (DefaultTableModel) jTableDonHang.getModel();
        if (select == -1) {
            JOptionPane.showMessageDialog(this, "Chọn sản phẩm !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else if(trangthai.equals("Xác nhận")) {
            try {
                int id = Integer.parseInt(model.getValueAt(select, 0).toString());
                dhDAO.updateVanChuyen(id);
                String ten=nccDAO.getTen(GiaoDienQuanLyNhaCungCapFrame.jLabelEmail.getText());
                dhDAO.setNhaCungCap(jTableDonHang,ten);
                JOptionPane.showMessageDialog(this, "Đơn hàng đã được vận chuyển", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Lỗi chuyển đổi dữ liệu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            
                JOptionPane.showMessageDialog(this, "Trạng thái không phù hợp!", "Lỗi", JOptionPane.ERROR_MESSAGE);
    
        }
    }//GEN-LAST:event_jButtonVanChuyenActionPerformed

    private void jTableDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDonHangMouseClicked
        model = (DefaultTableModel) jTableDonHang.getModel();
        int r = jTableDonHang.getSelectedRow();
        jTextFieldIDDonHang.setText(model.getValueAt(r, 0).toString());
        jTextFieldSanPham.setText(model.getValueAt(r, 1).toString());
        jTextFieldIDKhachHang.setText(model.getValueAt(r, 2).toString());
        jTextFieldtenKhachHang.setText(model.getValueAt(r, 4).toString());
        jTextFieldDiaChi.setText(model.getValueAt(r, 5).toString());
        jTextFieldSDT.setText(model.getValueAt(r, 6).toString());
        jTextFieldNgayMua.setText(model.getValueAt(r, 10).toString());
        jTextFieldSL.setText(model.getValueAt(r, 7).toString());
        jTextFieldTong.setText(model.getValueAt(r, 9).toString());
        jTextFieldTrangThai.setText(model.getValueAt(r, 12).toString());
    }//GEN-LAST:event_jTableDonHangMouseClicked

    private void jTextFieldIDDonHangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDDonHangKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldIDDonHangKeyTyped

    private void jTextFieldSanPhamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSanPhamKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldSanPhamKeyTyped

    private void jTextFieldIDKhachHangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDKhachHangKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldIDKhachHangKeyTyped

    private void jTextFieldtenKhachHangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldtenKhachHangKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldtenKhachHangKeyTyped

    private void jTextFieldDiaChiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDiaChiKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldDiaChiKeyTyped

    private void jTextFieldSDTKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSDTKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldSDTKeyTyped

    private void jTextFieldNgayMuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNgayMuaKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldNgayMuaKeyTyped

    private void jTextFieldSLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSLKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldSLKeyTyped

    private void jTextFieldTongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTongKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldTongKeyTyped

    private void jTextFieldTrangThaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTrangThaiKeyTyped
        evt.consume();
    }//GEN-LAST:event_jTextFieldTrangThaiKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoVanChuyenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoVanChuyenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoVanChuyenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoVanChuyenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChoVanChuyenFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVanChuyen;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDonHang;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextFieldDiaChi;
    private javax.swing.JTextField jTextFieldIDDonHang;
    private javax.swing.JTextField jTextFieldIDKhachHang;
    private javax.swing.JTextField jTextFieldNgayMua;
    private javax.swing.JTextField jTextFieldSDT;
    private javax.swing.JTextField jTextFieldSL;
    private javax.swing.JTextField jTextFieldSanPham;
    private javax.swing.JTextField jTextFieldTong;
    private javax.swing.JTextField jTextFieldTrangThai;
    private javax.swing.JTextField jTextFieldtenKhachHang;
    // End of variables declaration//GEN-END:variables
}
