/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package user;

import com.google.protobuf.Message;
import dao.DonHangDAO;
import dao.KhachHangDAO;
import dao.SanPhamDAO;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.DonHang;

/**
 *
 * @author ACER
 */
public class MuaHangFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserBuy
     */
    public MuaHangFrame() {
        initComponents();
        init();
    }
    int xx,yy;
    SanPhamDAO spDAO=new SanPhamDAO();
    DonHangDAO dhDAO=new DonHangDAO();
    KhachHangDAO khDAO=new KhachHangDAO();
    private int soluong=0;
    private double gia=0;
    private double tong=0;
    private int idDonHang=0;
    private String tenkhachhang;
    private double tinhtien=0;
    int r;
    DefaultTableModel model=new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void init(){
    
        idDonHang = dhDAO.khoiTaoID();
        jTextFieldID.setText(String.valueOf(dhDAO.khoiTaoID()));
        
        spDAO.loadData(jTableSanPham);
    
        tenkhachhang=khDAO.getTen(GiaoDienNguoiDungFrame.jLabelEmail.getText());
    }
    private void clear() {
        jTextFieldID.setText("");
        jTextFieldTen.setText("");
        jTextFieldSoLuong.setText("");

  
        jTableSanPham.clearSelection();
        jTableDonHang.clearSelection();

    }
    private void tableSanPham(){
    
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDonHang = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableSanPham = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldTen = new javax.swing.JTextField();
        jTextFieldSoLuong = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldThanhTien = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelTaiTrang = new javax.swing.JLabel();
        jDateChooserNgayMua = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Đơn hàng", "Khách hàng", "Tên sản phẩm", "Giá", "Số lượng", "Tổng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDonHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jTableDonHang);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 710, 400));

        jTableSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Sản phẩm", "Tên sản phẩm", "Danh mục", "Nhà cung cấp", "Giá", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSanPhamMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableSanPham);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 690, 400));

        jLabel11.setFont(new java.awt.Font("Snap ITC", 1, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("X");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Sản phẩm");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Đơn hàng");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 40, -1, -1));

        jTextFieldID.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldID.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jPanel1.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 300, -1));

        jTextFieldTen.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldTen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTenActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 300, -1));

        jTextFieldSoLuong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldSoLuongKeyTyped(evt);
            }
        });
        jPanel1.add(jTextFieldSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 300, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("ID Đơn hàng");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, -1, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Tên sản phẩm");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, -1, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Số lượng");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 620, -1, 20));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton1.setText("In hóa đơn");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 600, 110, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton2.setText("Xóa");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 550, 110, 40));

        jButton3.setBackground(new java.awt.Color(255, 255, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton3.setText("Mua");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 600, 110, 40));

        jButton4.setBackground(new java.awt.Color(255, 255, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton4.setText("Thêm");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 550, 110, 40));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Thành tiền");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 550, 120, 40));

        jTextFieldThanhTien.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextFieldThanhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldThanhTienActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 600, 140, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 1270, -1));

        jLabelTaiTrang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTaiTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reload.png"))); // NOI18N
        jLabelTaiTrang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelTaiTrang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTaiTrangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTaiTrangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTaiTrangMouseExited(evt);
            }
        });
        jPanel1.add(jLabelTaiTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jDateChooserNgayMua.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(jDateChooserNgayMua, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 640, 180, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Ngày mua");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jTextFieldTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTenActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int select=jTableDonHang.getSelectedRow();
        if(select==-1){
        
            JOptionPane.showMessageDialog(this, "Chọn sản phẩm !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else{
        
            double gia=(double)jTableDonHang.getValueAt(select, 3);
            double soluong=(int) jTableDonHang.getValueAt(select, 4);
            double tong=gia*soluong;
            tinhtien-=tong;
            jTextFieldThanhTien.setText(String.format("%.2f", tinhtien));
             model=(DefaultTableModel) jTableDonHang.getModel();
             model.removeRow(select);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldThanhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldThanhTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldThanhTienActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x=evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jLabelTaiTrangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTaiTrangMouseClicked
        clear();
    }//GEN-LAST:event_jLabelTaiTrangMouseClicked

    private void jLabelTaiTrangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTaiTrangMouseEntered
        jLabelTaiTrang.setText("Tải lại trang");
    }//GEN-LAST:event_jLabelTaiTrangMouseEntered

    private void jLabelTaiTrangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTaiTrangMouseExited
        jLabelTaiTrang.setText("");
    }//GEN-LAST:event_jLabelTaiTrangMouseExited

    private void jTableSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSanPhamMouseClicked
        model = (DefaultTableModel) jTableSanPham.getModel();
        r = jTableSanPham.getSelectedRow();
         

       
        jTextFieldTen.setText(model.getValueAt(r, 1).toString());

        soluong = Integer.parseInt(model.getValueAt(r, 5).toString());
        gia = Double.parseDouble(model.getValueAt(r, 4).toString());
    }//GEN-LAST:event_jTableSanPhamMouseClicked

    private void jTextFieldSoLuongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSoLuongKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldSoLuongKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jTextFieldSoLuong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nhập số lượng !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {

            if (!(soluong <= 0)) {
                int soluongnhap=Integer.parseInt(jTextFieldSoLuong.getText());
                if(soluongnhap!=0){
                if(!(soluongnhap>soluong)){
                
                    String tensanpham=jTextFieldTen.getText();
                    String tong=String.format("%.2f", gia*(double)soluongnhap);
                    Object[] row={idDonHang,tenkhachhang,jTextFieldTen.getText(),gia,soluongnhap,tong};
                    model=(DefaultTableModel) jTableDonHang.getModel();
                    model.addRow(row);
                    tinhtien+=gia*(double)soluongnhap;
                    jTextFieldThanhTien.setText(String.format("%.2f",tinhtien));
                    idDonHang++;
                    jTextFieldTen.setText("");
                    jTextFieldSoLuong.setText("");
                    clear();
                }
                else{
                JOptionPane.showMessageDialog(this, "Không đủ sản phẩm !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
                }
                else{
                JOptionPane.showMessageDialog(this, "Nhập số lượng lớn hơn 0 !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            } 
            else {
                JOptionPane.showMessageDialog(this, "Sản phẩm đã hết !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         model = (DefaultTableModel) jTableDonHang.getModel();
         String email=GiaoDienNguoiDungFrame.jLabelEmail.getText().toString();
        if (model.getRowCount() > 0) {

            for (int i = 0; i < model.getRowCount(); i++) {

                int id_donhang = Integer.parseInt(model.getValueAt(i, 0).toString());
                String tenkh = model.getValueAt(i, 1).toString();
                String tensp = model.getValueAt(i, 2).toString();
                double giatien = Double.parseDouble(model.getValueAt(i, 3).toString());
                int sl = Integer.parseInt(model.getValueAt(i, 4).toString());
                double tong=Double.parseDouble(model.getValueAt(i, 5).toString());
                java.util.Date utilNgayMua = jDateChooserNgayMua.getDate();
                java.sql.Date ngaymua = new java.sql.Date(utilNgayMua.getTime());
                int id_sp=spDAO.selectId(tensp);
                int id_kh=khDAO.getId(GiaoDienNguoiDungFrame.jLabelEmail.getText());
                DonHang dh = new DonHang(id_donhang, tensp, tenkh, giatien, sl,tong, ngaymua,null,"Chờ",id_sp,id_kh);
                dhDAO.insert(dh,email);
                int SLmoi = dhDAO.getSLSP(tensp) - sl;
                dhDAO.updateSanPham(tensp, SLmoi);

            }
            JOptionPane.showMessageDialog(this, "Mua hàng thành công !!!", "Thông báo", JOptionPane.ERROR_MESSAGE);

        } else {

            JOptionPane.showMessageDialog(this, "Giỏ hàng trống !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            tenkhachhang=khDAO.getTen(GiaoDienNguoiDungFrame.jLabelEmail.getText());
            MessageFormat mf = new MessageFormat("Hóa đơn " + "     "+ "Tổng tiền : " + tinhtien);
            MessageFormat mf2 = new MessageFormat("Page{0, number,integer}");
            jTableDonHang.print(JTable.PrintMode.FIT_WIDTH, mf, mf2);
        } catch (PrinterException e) {
            Logger.getLogger(DonHangDAO.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

   // private boolean  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MuaHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MuaHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MuaHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MuaHangFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MuaHangFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooserNgayMua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelTaiTrang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableDonHang;
    private javax.swing.JTable jTableSanPham;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldSoLuong;
    private javax.swing.JTextField jTextFieldTen;
    private javax.swing.JTextField jTextFieldThanhTien;
    // End of variables declaration//GEN-END:variables
}
