/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import dao.KhachHangDAO;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import model.KhachHang;
import model.NguoiDung;
/**
 *
 * @author ACER
 */
public class QuanLyNguoiDungFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserManagement
     */
    
    public QuanLyNguoiDungFrame() {
        initComponents();
        khDAO.loadData(jTableKhachHang);
    }
    int xx,yy;
    KhachHangDAO khDAO=new KhachHangDAO();
    DefaultTableModel model=new DefaultTableModel();
    NguoiDung nd=new NguoiDung() {
    };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private  boolean kiemTraKhongRong(){
    
        if(jTextFieldTen.getText().isEmpty()){
        
            JOptionPane.showMessageDialog(this, "Nhập họ tên !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(jTextFieldDiaChi.getText().isEmpty()){
        
            JOptionPane.showMessageDialog(this, "Nhập địa chỉ !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }if(jTextFieldSDT.getText().isEmpty()){
        
            JOptionPane.showMessageDialog(this, "Nhập số điện thoại !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(jTextFieldEmail.getText().isEmpty()){
        
            JOptionPane.showMessageDialog(this, "Nhập Email !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(String.valueOf(jPasswordFieldMatKhau.getPassword()).isEmpty()){
        
            JOptionPane.showMessageDialog(this, "Nhập mật khẩu ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(jDateChooserNgaySinh.getDate()==null){
        
            JOptionPane.showMessageDialog(this, "Điền ngày sinh !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if(jDateChooserNgaySinh.getDate()==null){
        
            JOptionPane.showMessageDialog(this, "Điền ngày đăng ký !!!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    private void clear() {
        jTextFieldID.setText("");
        jTextFieldTen.setText("");
        jTextFieldDiaChi.setText("");
        jTextFieldSDT.setText("");
        jTextFieldEmail.setText("");
        jPasswordFieldMatKhau.setText("");
        jDateChooserNgaySinh.setDate(null);
        jDateChooserNgayDangKy.setDate(null);
        jTableKhachHang.clearSelection();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDiaChi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSDT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDateChooserNgaySinh = new com.toedter.calendar.JDateChooser();
        jDateChooserNgayDangKy = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPasswordFieldMatKhau = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButtonTimKiem = new javax.swing.JButton();
        jTextFieldTuKhoa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKhachHang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabelTaiTrang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldID.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });
        jTextFieldID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldIDKeyTyped(evt);
            }
        });
        jPanel2.add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 350, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));
        jPanel2.add(jTextFieldTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 350, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Họ và tên");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));
        jPanel2.add(jTextFieldDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 350, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Địa chỉ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, -1));
        jPanel2.add(jTextFieldSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 350, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Số điện thoại");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, -1, -1));
        jPanel2.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 350, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Email");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Mật khẩu");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, -1, 20));

        jDateChooserNgaySinh.setDateFormatString("dd/MM/yyyy");
        jPanel2.add(jDateChooserNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 180, -1));

        jDateChooserNgayDangKy.setDateFormatString("dd/MM/yyyy");
        jPanel2.add(jDateChooserNgayDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, 180, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Ngày sinh");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Ngày đăng ký");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Cập nhật");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 150, 30));

        jLabel11.setFont(new java.awt.Font("Snap ITC", 1, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("X");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, 50, -1));
        jPanel2.add(jPasswordFieldMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 350, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Xóa tài khoản");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, 150, 30));

        jButtonTimKiem.setBackground(new java.awt.Color(255, 255, 0));
        jButtonTimKiem.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButtonTimKiem.setText("Tìm kiếm");
        jButtonTimKiem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTimKiemMouseClicked(evt);
            }
        });
        jButtonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, 150, 30));

        jTextFieldTuKhoa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel2.add(jTextFieldTuKhoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 620, 250, 30));

        jTableKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Họ và tên", "Địa chỉ", "Số điện thoại", "Email", "Mật khẩu", "Ngày sinh", "Ngày đăng ký"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableKhachHang);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 1040, 310));

        jLabel1.setText("________________________________________________________________________________________________________________________________________________________________________________");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hidden (1).png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 460, 30, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/show (1).png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 460, -1, -1));

        jLabelTaiTrang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTaiTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reload.png"))); // NOI18N
        jLabelTaiTrang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelTaiTrang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTaiTrangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelTaiTrangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelTaiTrangMouseExited(evt);
            }
        });
        jPanel2.add(jLabelTaiTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int id = Integer.parseInt(jTextFieldID.getText());
        String ten = jTextFieldTen.getText();
        String diaChi = jTextFieldDiaChi.getText();
        String sdt = jTextFieldSDT.getText();
        String email = jTextFieldEmail.getText();
        String matKhau = jPasswordFieldMatKhau.getText();
        java.util.Date utilNgaySinh = jDateChooserNgaySinh.getDate();
        java.sql.Date ngaySinh = new java.sql.Date(utilNgaySinh.getTime());
        java.util.Date utilNgayDangKy = jDateChooserNgayDangKy.getDate();
        java.sql.Date ngayDangKy = new java.sql.Date(utilNgayDangKy.getTime());
        nd = new KhachHang(id, ten, diaChi, sdt, email, matKhau, ngaySinh, ngayDangKy);
        int a = JOptionPane.showConfirmDialog(null, " Xác nhận xóa tài khoản", "Thông báo", JOptionPane.OK_CANCEL_OPTION, 0);
        if (a == JOptionPane.OK_OPTION) {

            khDAO.delete((KhachHang) nd);
            JOptionPane.showMessageDialog(null, " Tài khoản đã được xóa");
            QuanLyNguoiDungFrame ql = new QuanLyNguoiDungFrame();
            ql.setVisible(true);
            ql.pack();

            this.dispose();

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x=evt.getXOnScreen();
        int y= evt.getYOnScreen();
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

        jPasswordFieldMatKhau.setEchoChar((char) 0);
        jLabel13.setVisible(false);
        jLabel14.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        jPasswordFieldMatKhau.setEchoChar('*');
        jLabel13.setVisible(true);
        jLabel14.setVisible(false);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jTableKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKhachHangMouseClicked
        model=(DefaultTableModel) jTableKhachHang.getModel();
        int r=jTableKhachHang.getSelectedRow();
        jTextFieldID.setText(model.getValueAt(r, 0).toString());
        jTextFieldTen.setText(model.getValueAt(r, 1).toString());
        jTextFieldDiaChi.setText(model.getValueAt(r, 2).toString());
        jTextFieldSDT.setText(model.getValueAt(r, 3).toString());
        jTextFieldEmail.setText(model.getValueAt(r, 4).toString());
        jPasswordFieldMatKhau.setText(model.getValueAt(r, 5).toString());
        String ngaySinhString = model.getValueAt(r, 6).toString();
        String ngayDangKyString = model.getValueAt(r, 7 ).toString();
        java.sql.Date ngaySinhSql = java.sql.Date.valueOf(ngaySinhString);
        java.sql.Date ngayDangKySql = java.sql.Date.valueOf(ngayDangKyString);
        jDateChooserNgaySinh.setDate(ngaySinhSql);
        jDateChooserNgayDangKy.setDate(ngayDangKySql);

        
        
    }//GEN-LAST:event_jTableKhachHangMouseClicked

    private void jButtonTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTimKiemMouseClicked
        khDAO.search(jTableKhachHang);
        
    }//GEN-LAST:event_jButtonTimKiemMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(kiemTraKhongRong()){
        
            int id = Integer.parseInt(jTextFieldID.getText());
            String ten = jTextFieldTen.getText();
            String diaChi = jTextFieldDiaChi.getText();
            String sdt = jTextFieldSDT.getText();
            String email = jTextFieldEmail.getText();
            String matKhau = jPasswordFieldMatKhau.getText();
            java.util.Date utilNgaySinh = jDateChooserNgaySinh.getDate();
            java.sql.Date ngaySinh = new java.sql.Date(utilNgaySinh.getTime());
            java.util.Date utilNgayDangKy = jDateChooserNgayDangKy.getDate();
            java.sql.Date ngayDangKy = new java.sql.Date(utilNgayDangKy.getTime());
            nd = new KhachHang(id, ten, diaChi, sdt, email, matKhau, ngaySinh, ngayDangKy);
            if (!khDAO.kiemTraEmailKhongDuocThayDoi((KhachHang) nd)) {
                if (!khDAO.kiemTraIDKhongDuocThayDoi((KhachHang) nd)) {
                    khDAO.update((KhachHang) nd);
                    QuanLyNguoiDungFrame ql=new QuanLyNguoiDungFrame();
                    ql.setVisible(true);
                    ql.pack();
          
                    this.dispose();
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công ", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Không được thay đổi ID ", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Không được thay đổi Email ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabelTaiTrangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTaiTrangMouseClicked
        clear();
    }//GEN-LAST:event_jLabelTaiTrangMouseClicked

    private void jLabelTaiTrangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTaiTrangMouseEntered
         jLabelTaiTrang.setText("Tải lại trang");
    }//GEN-LAST:event_jLabelTaiTrangMouseEntered

    private void jLabelTaiTrangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTaiTrangMouseExited
        jLabelTaiTrang.setText("");
    }//GEN-LAST:event_jLabelTaiTrangMouseExited

    private void jTextFieldIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldIDKeyTyped
  
            evt.consume();
    }//GEN-LAST:event_jTextFieldIDKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNguoiDungFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNguoiDungFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNguoiDungFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNguoiDungFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNguoiDungFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonTimKiem;
    private com.toedter.calendar.JDateChooser jDateChooserNgayDangKy;
    private com.toedter.calendar.JDateChooser jDateChooserNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTaiTrang;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldMatKhau;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKhachHang;
    private javax.swing.JTextField jTextFieldDiaChi;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldSDT;
    private javax.swing.JTextField jTextFieldTen;
    private javax.swing.JTextField jTextFieldTuKhoa;
    // End of variables declaration//GEN-END:variables
}
